language: python

python:
    - "2.6"
    - "2.7"

env:
    global:
        - SSDB=./ssdb-server

install:
    - wget https://github.com/ideawu/ssdb/archive/master.zip
    - unzip master
    - make -C ssdb-master
    - mv ssdb-master/{ssdb-server,ssdb.conf} ./

script: nosetests -c setup.cfg
